server:
  port: 10000

logging:
  file: log/wangcl.log
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wangcl?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456789
    driver-class-name: com.mysql.jdbc.Driver
